# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# configure for jekyll V3.0
gems:                [jekyll-paginate]

# Setup
title:               c0d3r1991
tagline:             'Coding for fun'
description:         '热爱技术 <br/> 喜欢分享 <br/>'
url:                 http://shunde.github.io
baseurl:             ''
paginate:            20
paginate_path:       "page:num"
highlighter:         rouge
markdown:            kramdown



# About/contact
author:
  name:              c0d3r1991
  url:               http://weibo.com/wustcsd

# Custom vars
version:             1.0.0

# encoding
encoding:            utf-8

# information
github:             'https://github.com/shunde'